/**
 * BANNER TYPES REFERENCE
 * 
 * After running `npm run typegen`, the sanity.types.ts file will be automatically
 * updated with the Banner type definitions. This file documents the expected structure.
 * 
 * DO NOT EDIT THIS FILE - it's for reference only!
 */

/**
 * Example of the Banner type that will be generated.
 * The actual type definitions will be in sanity.types.ts
 */

/*
export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  buttonText?: string;
  buttonLink?: string;
  altText?: string;
  isActive?: boolean;
  order?: number;
  mobileImage?: SanityImage;
  tabletImage?: SanityImage;
  desktopImage?: SanityImage;
};

export type SanityImage = {
  asset?: {
    _ref: string;
    _type: "reference";
  };
  hotspot?: {
    x: number;
    y: number;
    height: number;
    width: number;
  };
  crop?: {
    top: number;
    bottom: number;
    left: number;
    right: number;
  };
  _type: "image";
};
*/

/**
 * GROQ Query Result Type
 * 
 * The getAllBanners() query will return:
 */

/*
export type ALL_BANNERS_QUERYResult = Array<{
  _id: string;
  title?: string;
  description?: string;
  buttonText?: string;
  buttonLink?: string;
  altText?: string;
  mobileImage?: {
    asset?: {
      _id: string;
      url?: string;
    };
    hotspot?: { x: number; y: number; height: number; width: number };
    crop?: { top: number; bottom: number; left: number; right: number };
  };
  tabletImage?: {
    asset?: {
      _id: string;
      url?: string;
    };
    hotspot?: { x: number; y: number; height: number; width: number };
    crop?: { top: number; bottom: number; left: number; right: number };
  };
  desktopImage?: {
    asset?: {
      _id: string;
      url?: string;
    };
    hotspot?: { x: number; y: number; height: number; width: number };
    crop?: { top: number; bottom: number; left: number; right: number };
  };
}>;
*/

/**
 * To regenerate types after schema changes, run:
 * npm run typegen
 * 
 * This will update sanity.types.ts with the latest type definitions.
 */
