/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

import { SanityDocument, Slug, Image } from 'sanity';

export interface Category extends SanityDocument {
  title: string;
  slug: Slug;
  description?: string;
  image?: Image;
}

export interface Product extends SanityDocument {
  name: string;
  slug: Slug;
  images?: Image[];
  intro?: string;
  description?: string;
  price: number;
  discount: number;
  categories?: Category[];
  stock?: number;
  status?: 'new' | 'hot' | 'sale';
  variant?: 'tshirt' | 'jacket' | 'pants' | 'hoodie' | 'short' | 'others';
  size?: ('XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL')[];
}